name: Build tool on OSX
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    env:
      LDFLAGS:  "-L/opt/homebrew/opt/llvm@14/lib"
      CPPFLAGS: "-I/opt/homebrew/opt/llvm@14/include"
